name: Deploy to GKE

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: tourguide-393611
  GKE_CLUSTER: tg-kube-cluster
  GKE_ZONE: europe-southwest1
  DEPLOYMENT_NAME: tg-multimedia-service
  CONTAINER: gcr.io/tourguide-393611/tg-multimedia-service

jobs:
  build_application:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 20
      uses: actions/setup-java@v2
      with:
        java-version: '20'
        distribution: 'adopt'
        maven-version: '4.0.0'

    - name: Build maven package
      run: mvn package

  setup_gcloud:
    runs-on: ubuntu-latest
    steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.TOURGUIDE_GKE_GITHUB_DEPLOY_KEY }}

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        install_components: kubectl

    - name: Configure Docker
      run: gcloud --quiet auth configure-docker

    - name: Connect kubectl to GKE
      run: gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }}

  docker_build_push:
    needs: [build_application, setup_gcloud]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ env.CONTAINER }}:latest .
        docker push ${{ env.CONTAINER }}:latest

  deploy:
    needs: docker_build_push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create ConfigMaps if Not Exist
      run: |
        kubectl get configmap multimedia-config || kubectl create configmap multimedia-config --from-literal=SPRING_PROFILES_ACTIVE=prod

    - name: Deploy to GKE
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
